import {useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {client,configured,reauthenticate,rpc,signInGoogle,type Group,type Snapshot} from './api';
import {authError,definitelyRejected,message} from './errors';
import {captureInvite,invitationToken,storedInvite} from './invitations';
import {clearPending,readPending,type PendingExpense} from './pendingExpense';
import {useHousehold} from './useHousehold';
import {useRoute,type Screen} from './navigation';
import {useMutation} from './useMutation';
import {ActionDialog,Recovery,type Prompt} from './actions';
import {ExpenseForm} from './ExpenseForm';
import {GroupForm,InviteForm,JoinForm} from './GroupForms';
import {Balances,Expenses,Home,PaymentForm,type Navigate} from './HouseholdViews';
import {Shopping} from './Shopping';
import {Activity,People,Settings} from './Management';
import {Alert,Brand,FormHeader,Icon,Loading,moveToTop,type IconName} from './ui';
import {money} from './money';
export function App(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[signingIn,setSigningIn]=useState(false),[attempt,setAttempt]=useState(0);const flight=useRef(false);
 useEffect(()=>{if(!client)return;let active=true;const timeout=setTimeout(()=>{if(active){setError('Connecting is taking longer than usual. Check your connection and try again.');setReady(true);}},15000);
 function receive(next:Session|null){if(!active)return;if(next){try{const target=sessionStorage.getItem('pact:return-to');if(target&&target.startsWith('/')&&!target.startsWith('//')){sessionStorage.removeItem('pact:return-to');const url=new URL(target,location.origin);if(url.origin===location.origin)history.replaceState({pact:true},'',url.pathname+url.search);}}catch{/* Keep the current route. */}setError('');}clearTimeout(timeout);setSession(next);setReady(true);}
 client.auth.getSession().then(({data,error})=>{if(error)throw error;receive(data.session);}).catch(e=>{if(active){clearTimeout(timeout);setError(message(e));setReady(true);}});
 const {data:listener}=client.auth.onAuthStateChange((_event,next)=>receive(next));const reset=()=>{flight.current=false;setSigningIn(false);};window.addEventListener('pageshow',reset);return()=>{active=false;clearTimeout(timeout);listener.subscription.unsubscribe();window.removeEventListener('pageshow',reset);};},[attempt]);
 async function signIn(){if(flight.current)return;flight.current=true;setSigningIn(true);setError('');try{await signInGoogle();}catch(e){setError(message(e));flight.current=false;setSigningIn(false);}}
 if(!configured)return <main className="welcome"><Brand/><h1>Pact is getting ready.</h1><p>The app owner needs to finish connecting this version.</p></main>;
 if(!ready)return <main className="welcome"><Brand/><Loading text="Opening Pact…"/></main>;
 if(!session)return <main className="welcome"><Brand/><span className="welcome-symbol" aria-hidden="true"><Icon name="home"/></span><p className="eyebrow">Shared life, sorted</p><h1>Less organising.<br/>More living.</h1><p className="intro muted">Shared expenses, a shopping list and the occasional trip. All in one simple place.</p>{(storedInvite()||invitationToken(location.href))&&<p className="callout">Your invitation is ready. Sign in with the Google account it was created for.</p>}<Alert text={error}><button onClick={()=>{setReady(false);setError('');setAttempt(n=>n+1);}}>Try connecting again</button></Alert><button className="primary full google-button" disabled={signingIn} onClick={signIn}><span aria-hidden="true" className="google-g">G</span>{signingIn?'Opening Google…':'Continue with Google'}</button><p className="helper">Your household’s information is visible to its members.</p></main>;
 return <Workspace key={session.user.id} session={session}/>;
}
const tabs:{id:Screen;label:string;icon:IconName}[]=[{id:'home',label:'Home',icon:'home'},{id:'shopping',label:'Shopping',icon:'shopping'},{id:'expenses',label:'Expenses',icon:'expense'},{id:'balances',label:'Balances',icon:'balance'}];
function Workspace({session}:{session:Session}){
 const userId=session.user.id;const {route,navigate:go,back}=useRoute();const household=useHousehold(userId,route.group);
 const {groups,group,groupId,snapshot,loaded,groupError,dataError,online,refreshing,live,loadGroups,refresh,loadMore}=household;
 const [joinToken,setJoinToken]=useState(()=>captureInvite()),[notice,setNotice]=useState(''),[error,setError]=useState(''),[signingOut,setSigningOut]=useState(false);
 const navigate:Navigate=(screen,options={},replace=false)=>{setNotice('');setError('');go(screen,{group:groupId,...options},replace);};
 useEffect(()=>{if(joinToken)go('join',{},true);},[]);
 useEffect(()=>{const handle=()=>{if(!invitationToken(location.href))return;setJoinToken(captureInvite());go('join');};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle);},[route]);
 useEffect(moveToTop,[route.screen,route.group,route.edit,route.purchase]);
 async function created(id:string,joined=false){if(!await loadGroups(id))return false;go(joined?'home':'people',{group:id},true);setJoinToken('');setNotice(joined?'You’ve joined. Welcome!':'Created. Your shared space is ready.');return true;}
 async function signOut(){if(!client||signingOut)return;setSigningOut(true);setError('');try{const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;}catch(e){setError(message(e));setSigningOut(false);}}
 const independent=['account','groups','household','trip','join'].includes(route.screen);const primary=tabs.some(t=>t.id===route.screen);const parentId=group?.kind==='household'?group.id:group?.parent_household_id??undefined;
 return <div className={`app-shell ${group&&primary?'with-nav':''}`}><header className="app-header"><div className="topbar"><button className="brand-button" aria-label="Pact home" onClick={()=>navigate('home')}><Brand/></button><button className="text-button account-button" onClick={()=>navigate('account')}>Account</button></div>{group&&!independent&&<div className="group-header"><button className="current-group" onClick={()=>navigate('groups')}><Icon name={group.kind==='trip'?'trip':'home'}/><span className="truncate">{group.name}</span><Icon name="down"/></button><button className="icon-button" aria-label="Household menu" onClick={()=>navigate('groups')}><Icon name="menu"/></button></div>}</header><main className="main-content">
 {!online&&<p className="callout" role="status">You’re offline. Your draft stays on this device. Reconnect to save or load changes.</p>}{notice&&<div className="notice" role="status"><Icon name="check"/><span>{notice}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setNotice('')}><Icon name="close"/></button></div>}<Alert text={error}/>
 {(route.screen==='household'||route.screen==='trip')&&<GroupForm key={route.screen} kind={route.screen} groups={groups} initialParent={parentId} online={online} userId={userId} onBack={()=>back()} onCreated={created}/>}
 {route.screen==='join'&&<JoinForm key={joinToken} initialToken={joinToken} email={session.user.email??''} online={online} onBack={()=>back()} onJoined={id=>created(id,true)}/>}
 {route.screen==='account'&&<section className="form-page"><FormHeader title="Your account" context="Pact" onBack={()=>back()}/><p className="eyebrow">Signed in with Google</p><p className="account-email break-word">{session.user.email}</p><div className="stack-actions"><button onClick={()=>void reauthenticate().catch(e=>setError(message(e)))} disabled={!online}>Switch Google account</button><button onClick={signOut} disabled={signingOut}>{signingOut?'Signing out…':'Sign out'}</button></div><section className="card"><h2>Using Pact</h2><p>Add what you paid, then select exactly who shares the cost. Use Shopping for things to buy and Balances to settle up.</p><p className="muted">Drafts and unfinished saves stay on this browser. For a shared device, use a separate browser profile.</p></section><p className="helper">Pact 0.3 · AUD · Melbourne time</p><details className="history-section"><summary>Add Pact to your home screen</summary><p>On iPhone, open Pact in Safari, tap Share, then Add to Home Screen. On Android, use the browser menu’s install or home screen option.</p><p className="helper">An internet connection is needed to sync and save.</p></details></section>}
 {route.screen==='groups'&&<section className="form-page"><FormHeader title="Your households & trips" context="Pact" onBack={()=>back()}/>{group&&<div className="menu-grid"><button onClick={()=>navigate('people')}><Icon name="people"/>People & trips</button><button onClick={()=>navigate('activity')}><Icon name="clock"/>Activity</button><button onClick={()=>navigate('settings')}><Icon name="menu"/>Settings & exports</button></div>}{(['household','trip'] as const).map(kind=><section className="group-section" key={kind}><h2>{kind==='household'?'Households':'Trips'}</h2><div className="group-list">{groups.filter(g=>g.kind===kind).map(g=><button key={g.id} onClick={()=>navigate('home',{group:g.id})}><Icon name={kind==='trip'?'trip':'home'}/><span>{g.name}{g.archived_at&&<small>Archived</small>}</span>{g.id===groupId&&<Icon name="check"/>}</button>)}</div>{!groups.some(g=>g.kind===kind)&&<p className="muted">None yet.</p>}</section>)}<div className="stack-actions">{groups.some(g=>g.kind==='household'&&!g.archived_at)&&<button onClick={()=>navigate('trip')} disabled={!online}>Create a trip</button>}<button onClick={()=>navigate('household')} disabled={!online}>Create a household</button><button className="text-button" onClick={()=>navigate('join')}>Join with an invitation</button></div></section>}
 {!independent&&<><Alert text={groupError}><button disabled={refreshing||!online} onClick={()=>void refresh()}>Refresh households</button><button onClick={()=>void reauthenticate().catch(e=>setError(message(e)))}>Sign in again</button></Alert>{!loaded?!groupError&&<Loading/>:route.group&&!groups.some(g=>g.id===route.group)?<><ScreenHeadingFallback/><p className="muted">This household or trip is no longer available to your account. Its previous records are kept.</p><LostAccessRecovery userId={userId} groupId={route.group} online={online}/><button onClick={()=>navigate('groups',{group:''})}>Your households & trips</button></>:route.group&&group?.id!==route.group?<Loading/>:!group?<section className="onboarding"><span className="empty-icon"><Icon name="home"/></span><h1 tabIndex={-1} data-screen-heading>Let’s set up your home.</h1><p className="intro muted">Create one household, then invite your flatmates.</p><button className="primary full" disabled={!online} onClick={()=>navigate('household')}>Create a household</button><button className="text-button full" onClick={()=>navigate('join')}>I have an invitation</button></section>:<>{group.archived_at&&<p className="callout">Archived · History is available. An organiser can reopen this group in Settings.</p>}<Alert text={dataError}><button onClick={()=>void refresh()} disabled={refreshing||!online}>Refresh</button><button onClick={()=>void reauthenticate().catch(e=>setError(message(e)))}>Sign in again</button></Alert>{!snapshot?!dataError&&<Loading/>:<GroupArea key={group.id} {...{group,groups,snapshot,userId,online,route,navigate,refresh,loadMore}} back={()=>back()} onNotice={setNotice}/>}<div className="refresh-row"><span className="helper">{!online?'Offline':!live?'Checking for updates every 30 seconds':'Live updates on'}</span><button className="text-button" disabled={refreshing||!online} onClick={()=>void refresh()}>{refreshing?'Refreshing…':'Refresh'}</button></div></>}</>}
 </main>{group&&primary&&<nav className="bottom-nav" aria-label="Main navigation">{tabs.map(t=><button key={t.id} aria-current={route.screen===t.id?'page':undefined} onClick={()=>navigate(t.id)}><Icon name={t.icon}/><span>{t.label}</span></button>)}</nav>}</div>;
}
function ScreenHeadingFallback(){return <h1 tabIndex={-1} data-screen-heading>Access has changed</h1>;}
function GroupArea({group,groups,snapshot,userId,online,route,navigate,refresh,loadMore,back,onNotice}:{group:Group;groups:Group[];snapshot:Snapshot;userId:string;online:boolean;route:ReturnType<typeof useRoute>['route'];navigate:Navigate;refresh:()=>Promise<void>;loadMore:()=>Promise<void>;back:()=>void;onNotice:(value:string)=>void}){
 const mutation=useMutation(userId,group.id,async()=>{await refresh();onNotice('Saved.');});const [prompt,setPrompt]=useState<Prompt|null>(null);
 const props={group,snapshot,userId,online,mutation,navigate,ask:setPrompt};let pending:PendingExpense|null=null,recoveryError='';try{pending=readPending(userId,group.id);}catch(e){recoveryError=message(e);}
 const initial=route.edit?snapshot.expenses.find(e=>e.id===route.edit):undefined;const purchase=route.purchase?snapshot.purchases.find(p=>p.id===route.purchase):undefined;const purchaseName=snapshot.shopping.find(i=>i.id===purchase?.item_id)?.name;
 const form=route.screen==='expense';const isOrganiser=snapshot.members.some(m=>m.id===userId&&m.role==='organiser'&&m.status==='active');
 return <><Recovery mutation={mutation} online={online}/><Alert text={recoveryError}/>{pending&&!form&&<div className="callout recovery"><div><strong>An expense save needs checking</strong><p>Check the original request before adding another expense.</p></div><button onClick={()=>navigate('expense')}>Check save</button></div>}{!tabs.some(t=>t.id===route.screen)&&!form&&route.screen!=='invite'&&<div className="form-top"><button className="text-button" onClick={back}><Icon name="back"/>Back</button></div>}
 {route.screen==='home'&&<Home {...props}/>} {route.screen==='shopping'&&<Shopping {...props}/>} {route.screen==='expenses'&&<Expenses {...props} loadMore={loadMore}/>} {route.screen==='balances'&&<Balances {...props}/>} {route.screen==='people'&&<People {...props} groups={groups}/>} {route.screen==='activity'&&<Activity {...props}/>} {route.screen==='settings'&&<Settings {...props}/>}
 {route.screen==='payment'&&<PaymentForm key={route.to+route.amount} {...props} route={route}/>} {route.screen==='invite'&&(isOrganiser&&!group.archived_at?<InviteForm group={group} online={online} onBack={back}/>:<p className="callout">An organiser can invite people to an active household.</p>)}
 {form&&(!pending&&(group.archived_at||route.edit&&!initial||route.purchase&&!purchase||initial&&(initial.status!=='posted'||initial.created_by!==userId&&!isOrganiser))?<><p className="callout">This expense is not available to edit. Refresh your expenses and try again.</p><button onClick={()=>navigate('expenses')}>Back to expenses</button></>:<ExpenseForm key={route.edit||route.purchase||'new'} group={group} snapshot={snapshot} userId={userId} online={online} initial={initial} purchaseId={purchase?.id} purchaseName={purchaseName} onBack={back} onSaved={()=>{navigate('expenses',{},true);onNotice('Expense saved.');void refresh();}}/>)}
 {prompt&&<ActionDialog prompt={prompt} busy={mutation.busy} blocked={!online||!!mutation.pending} onClose={()=>setPrompt(null)}/>}</>;
}
function LostAccessRecovery({userId,groupId,online}:{userId:string;groupId:string;online:boolean}){
 const [pending,setPending]=useState(()=>{try{return readPending(userId,groupId);}catch{return null;}}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[needsAuth,setNeedsAuth]=useState(false);const mutation=useMutation(userId,groupId,()=>setResult('The earlier action was saved.'));
 async function check(){if(!pending||busy)return;setBusy(true);setError('');try{if(pending.legacy)await rpc('create_expense',pending.input);else await rpc('save_expense',{p_input:pending.input,p_replaces:pending.replaces??null,p_version:pending.version??null,p_reason:pending.reason??'',p_purchase:pending.purchase??null});clearPending(userId,groupId);setPending(null);setResult('The earlier expense was saved. Your access to the group has since changed.');}catch(e){if(authError(e))setNeedsAuth(true);else if(definitelyRejected(e)){clearPending(userId,groupId);setPending(null);}setError(message(e));}finally{setBusy(false);}}
 return <><Recovery mutation={mutation} online={online}/>{pending&&<div className="callout"><p>Check your earlier save: {pending.input.p_description} · {money(pending.input.p_amount)}</p><button disabled={!online||busy} onClick={()=>void check()}>{busy?'Checking…':'Check expense save'}</button></div>}{result&&<p className="notice">{result}</p>}<Alert text={error}>{needsAuth&&<button onClick={()=>void reauthenticate().catch(e=>setError(message(e)))}>Sign in again</button>}</Alert></>;
}
