import {useEffect,useRef,useState,type FormEvent} from 'react';
import {reauthenticate,rpc,type Group,type Member,type Snapshot} from './api';
import {message} from './errors';
import {clearInvite,invitationToken,rememberInvite} from './invitations';
import {useMutation} from './useMutation';
import {Recovery} from './actions';
import {Alert,FormHeader,Icon,Loading,moveToTop} from './ui';
type FormProps={onBack:()=>void;online:boolean};
export function GroupForm({kind,groups,initialParent,onBack,online,onCreated,userId}:FormProps&{kind:'household'|'trip';groups:Group[];initialParent?:string;onCreated:(id:string)=>Promise<boolean>;userId:string}) {
 const households=groups.filter(g=>g.kind==='household'&&!g.archived_at);
 const [name,setName]=useState(''),[parent,setParent]=useState(households.find(g=>g.id===initialParent)?.id??households[0]?.id??'');
 const [people,setPeople]=useState<string[]>([]),[members,setMembers]=useState<Member[]|null>(null),[error,setError]=useState('');
 const mutation=useMutation(userId,`create-${kind}`,async id=>{if(!await onCreated(String(id)))throw new Error('Load failed');});
 const locked=mutation.busy||!!mutation.pending;
 useEffect(()=>{if(kind!=='trip'||!parent)return;let active=true;setMembers(null);setError('');void rpc<Snapshot>('get_household_state',{p_group:parent,p_limit:1}).then(s=>{if(active){setMembers(s.members.filter(m=>m.status==='active'));setPeople([]);}}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[parent,kind]);
 async function submit(event:FormEvent){event.preventDefault();if(locked||!online)return;await mutation.run('create_space',{p_name:name.trim(),p_kind:kind,p_parent:kind==='trip'?parent:null,p_people:kind==='trip'?people:[]},`Create ${kind}`);}
 return <section className="form-page"><FormHeader title={kind==='trip'?'Create a trip':'Create your household'} context="Pact" onBack={onBack} disabled={mutation.busy}/><p className="muted">{kind==='trip'?'Choose who is going. Trip costs stay separate from household costs.':'One shared place for your flatmates, expenses and shopping.'}</p><Recovery mutation={mutation} online={online}/><form onSubmit={submit}><label>{kind==='trip'?'Trip name':'Household name'}<input required maxLength={80} value={name} disabled={locked} onChange={e=>setName(e.target.value)} placeholder={kind==='trip'?'Weekend away':'Our home'}/></label>{kind==='trip'&&<><label>Household<select required value={parent} disabled={locked} onChange={e=>setParent(e.target.value)}>{households.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><fieldset><legend>Who is going?</legend><p className="helper">You are included as the trip organiser.</p>{!members&&!error?<Loading text="Loading people…"/>:<div className="list-panel">{members?.filter(m=>m.id!==userId).map(m=><label className="check-row" key={m.id}><input type="checkbox" disabled={locked} checked={people.includes(m.id)} onChange={e=>setPeople(old=>e.target.checked?[...old,m.id]:old.filter(id=>id!==m.id))}/>{m.name}</label>)}</div>}</fieldset></>}<Alert text={error}/><button className="primary full" disabled={locked||!online||(kind==='trip'&&(!parent||!members))}>{mutation.busy?'Creating…':`Create ${kind}`}</button>{kind==='household'&&<p className="helper">Invite your flatmates on the next screen.</p>}</form></section>;
}
export function JoinForm({initialToken,email,onBack,online,onJoined}:FormProps&{initialToken:string;email:string;onJoined:(id:string)=>Promise<boolean>}) {
 const [value,setValue]=useState(initialToken),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const joined=useRef(''),flight=useRef(false);
 async function submit(event:FormEvent){event.preventDefault();if(flight.current||!online)return;const token=invitationToken(value);if(!token){setError('Paste the complete invitation link or its 64-character code.');return;}rememberInvite(token);flight.current=true;setBusy(true);setError('');try{if(!joined.current)joined.current=await rpc<string>('accept_invitation',{p_token:token});if(await onJoined(joined.current))clearInvite();else setError('You have joined. Try opening the household again.');}catch(e){setError(message(e));}finally{flight.current=false;setBusy(false);}}
 async function switchAccount(){setError('');try{if(value&&!rememberInvite(value))throw new Error('Paste a valid invitation before switching accounts.');await reauthenticate();}catch(e){setError(message(e));}}
 return <section className="form-page"><FormHeader title="Join your people" context="Pact" onBack={onBack} disabled={busy}/><p className="muted">Joining as <strong className="break-word">{email}</strong>.</p><button className="text-button" disabled={busy||!online} onClick={()=>void switchAccount()}>Use a different Google account</button><form onSubmit={submit}><label>Invitation link or code<input required value={value} disabled={busy||!!joined.current} onChange={e=>setValue(e.target.value)} placeholder="Paste your invitation" autoComplete="off" autoCapitalize="none" spellCheck={false}/></label><p className="helper">Sign in with the Google email your invitation was created for.</p><Alert text={error}/><button className="primary full" disabled={busy||!online}>{busy?'Joining…':joined.current?'Open household or trip':'Accept invitation'}</button></form></section>;
}
export function InviteForm({group,onBack,online}:FormProps&{group:Group}) {
 const [email,setEmail]=useState(''),[recipient,setRecipient]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const flight=useRef(false);
 async function submit(event:FormEvent){event.preventDefault();if(flight.current||!online)return;const submitted=email.trim().toLowerCase();flight.current=true;setBusy(true);setError('');setCopied(false);try{const token=await rpc<string>('create_invitation',{p_group:group.id,p_email:submitted});setRecipient(submitted);setLink(`${location.origin}/#invite=${token}`);moveToTop();}catch(e){setError(message(e));}finally{flight.current=false;setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(link);setCopied(true);setError('');}catch{setError('Select and copy the invitation link below.');}}
 async function share(){try{await navigator.share({title:`Join ${group.name} on Pact`,text:'Join our household on Pact.',url:link});}catch(e){if((e as Error).name!=='AbortError')setError('Sharing did not open. Use Copy link instead.');}}
 return <section className="form-page"><FormHeader title={link?'Share the invitation':'Invite a flatmate'} context={group.name} onBack={onBack} disabled={busy}/>{link?<><p className="muted">Send this link to <strong className="break-word">{recipient}</strong>. They can open it and sign in with that Google account.</p><div className="share-actions"><button className="primary" onClick={copy}>{copied&&<Icon name="check"/>}{copied?'Copied':'Copy link'}</button>{typeof navigator.share==='function'&&<button onClick={share}>Share…</button>}</div><p className="helper" role="status">{copied?'Link copied. Paste it into your message.':'Expires in 7 days. No email is sent automatically.'}</p><label>Invitation link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><Alert text={error}/><div className="form-actions"><button onClick={()=>{setLink('');setEmail('');setCopied(false);setError('');}}>Invite another person</button><button onClick={onBack}>Done</button></div></>:<form onSubmit={submit}><p className="muted">Enter their Google email, then share their personal invitation link.</p><label>Google email<input required disabled={busy} type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@gmail.com" autoComplete="email" autoCapitalize="none" spellCheck={false}/></label><Alert text={error}/><button className="primary full" disabled={busy||!online}>{busy?'Creating link…':'Create invitation link'}</button></form>}</section>;
}
